CREATE TABLE `SAMPLE_USER` (
  `ID` varchar(255) NOT NULL,
  `AGE` int(11) NOT NULL,
  `LAST_NAME` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;